export interface DatabaseTemplate {
  id: string;
  name: string;
  description: string;
  category: 'Project Management' | 'Governance' | 'Business' | 'Strategy';
  icon: string;
  columns: Array<{
    name: string;
    type: string;
    options?: string[];
    width?: number;
  }>;
  sampleRows: Array<Record<string, any>>;
}

export const DATABASE_TEMPLATES: DatabaseTemplate[] = [
  {
    id: "project-task-tracker",
    name: "Project & Task Tracker",
    description: "Track tasks across projects with priorities, owners, and progress tracking.",
    category: "Project Management",
    icon: "clipboard-list",
    columns: [
      { name: "Task Title", type: "text", width: 250 },
      { name: "Project", type: "text", width: 180 },
      { name: "Description", type: "text", width: 300 },
      { name: "Status", type: "select", options: ["Not Started", "In Progress", "On Hold", "Completed"], width: 140 },
      { name: "Priority", type: "select", options: ["Critical", "High", "Medium", "Low"], width: 120 },
      { name: "Owner", type: "person", width: 150 },
      { name: "Due Date", type: "date", width: 130 },
      { name: "Start Date", type: "date", width: 130 },
      { name: "Tags", type: "multi_select", options: ["Frontend", "Backend", "Design", "Testing", "Documentation"], width: 200 },
      { name: "Dependencies", type: "text", width: 200 },
      { name: "Effort Estimate", type: "number", width: 130 },
      { name: "% Complete", type: "number", width: 120 },
    ],
    sampleRows: [
      {
        "Task Title": "Implement user authentication flow",
        "Project": "Customer Portal v2",
        "Description": "Build login, registration, and password reset functionality with OAuth support.",
        "Status": "In Progress",
        "Priority": "High",
        "Owner": "Sarah Chen",
        "Due Date": "2026-03-28",
        "Start Date": "2026-03-10",
        "Tags": ["Frontend", "Backend"],
        "Dependencies": "Database schema migration",
        "Effort Estimate": 16,
        "% Complete": 45,
      },
      {
        "Task Title": "Design dashboard wireframes",
        "Project": "Analytics Platform",
        "Description": "Create wireframes for the main analytics dashboard including chart layouts and filters.",
        "Status": "Completed",
        "Priority": "Medium",
        "Owner": "James Wilson",
        "Due Date": "2026-03-15",
        "Start Date": "2026-03-01",
        "Tags": ["Design", "Documentation"],
        "Dependencies": "",
        "Effort Estimate": 8,
        "% Complete": 100,
      },
      {
        "Task Title": "Set up CI/CD pipeline",
        "Project": "Infrastructure Modernisation",
        "Description": "Configure automated build, test, and deployment pipelines for all microservices.",
        "Status": "Not Started",
        "Priority": "Critical",
        "Owner": "Priya Patel",
        "Due Date": "2026-04-10",
        "Start Date": "2026-03-25",
        "Tags": ["Backend", "Testing"],
        "Dependencies": "Cloud environment provisioning",
        "Effort Estimate": 24,
        "% Complete": 0,
      },
    ],
  },
  {
    id: "kanban-workflow-board",
    name: "Kanban Workflow Board",
    description: "Manage work items through workflow stages with visual card-based tracking.",
    category: "Project Management",
    icon: "columns",
    columns: [
      { name: "Card Title", type: "text", width: 250 },
      { name: "Stage", type: "select", options: ["Backlog", "To Do", "In Progress", "In Review", "Done"], width: 140 },
      { name: "Owner", type: "person", width: 150 },
      { name: "Priority", type: "select", options: ["Urgent", "High", "Medium", "Low"], width: 120 },
      { name: "Type", type: "select", options: ["Feature", "Bug", "Improvement", "Task"], width: 130 },
      { name: "Tags", type: "multi_select", options: ["Frontend", "Backend", "API", "UX", "DevOps"], width: 200 },
      { name: "Created Date", type: "date", width: 130 },
      { name: "Due Date", type: "date", width: 130 },
      { name: "Blocked", type: "checkbox", width: 100 },
      { name: "Related Project", type: "text", width: 180 },
    ],
    sampleRows: [
      {
        "Card Title": "Add export to CSV functionality",
        "Stage": "In Progress",
        "Owner": "Marcus Lee",
        "Priority": "High",
        "Type": "Feature",
        "Tags": ["Frontend", "API"],
        "Created Date": "2026-03-05",
        "Due Date": "2026-03-20",
        "Blocked": false,
        "Related Project": "Reporting Module",
      },
      {
        "Card Title": "Fix pagination on search results",
        "Stage": "In Review",
        "Owner": "Elena Kowalski",
        "Priority": "Urgent",
        "Type": "Bug",
        "Tags": ["Frontend", "UX"],
        "Created Date": "2026-03-12",
        "Due Date": "2026-03-18",
        "Blocked": false,
        "Related Project": "Customer Portal v2",
      },
      {
        "Card Title": "Refactor notification service",
        "Stage": "Backlog",
        "Owner": "David Okafor",
        "Priority": "Medium",
        "Type": "Improvement",
        "Tags": ["Backend", "DevOps"],
        "Created Date": "2026-02-28",
        "Due Date": "2026-04-15",
        "Blocked": true,
        "Related Project": "Platform Infrastructure",
      },
    ],
  },
  {
    id: "meeting-actions-tracker",
    name: "Meeting Actions Tracker",
    description: "Capture and track action items arising from meetings with ownership and deadlines.",
    category: "Project Management",
    icon: "list-checks",
    columns: [
      { name: "Action Title", type: "text", width: 250 },
      { name: "Meeting Name", type: "text", width: 200 },
      { name: "Date Raised", type: "date", width: 130 },
      { name: "Action Owner", type: "person", width: 150 },
      { name: "Due Date", type: "date", width: 130 },
      { name: "Status", type: "select", options: ["Open", "In Progress", "Done", "Deferred"], width: 130 },
      { name: "Priority", type: "select", options: ["High", "Medium", "Low"], width: 120 },
      { name: "Source Meeting Link", type: "url", width: 200 },
      { name: "Notes", type: "text", width: 300 },
      { name: "Closure Date", type: "date", width: 130 },
    ],
    sampleRows: [
      {
        "Action Title": "Draft revised project timeline for Q2",
        "Meeting Name": "Programme Review - March",
        "Date Raised": "2026-03-10",
        "Action Owner": "Sarah Chen",
        "Due Date": "2026-03-17",
        "Status": "In Progress",
        "Priority": "High",
        "Source Meeting Link": "https://meetings.example.com/prog-review-mar",
        "Notes": "Include updated resource allocations and dependency mapping.",
        "Closure Date": "",
      },
      {
        "Action Title": "Schedule vendor demo for analytics tool",
        "Meeting Name": "Technology Steering Committee",
        "Date Raised": "2026-03-08",
        "Action Owner": "James Wilson",
        "Due Date": "2026-03-22",
        "Status": "Open",
        "Priority": "Medium",
        "Source Meeting Link": "https://meetings.example.com/tech-steering-mar",
        "Notes": "Contact three shortlisted vendors for 1-hour demo slots.",
        "Closure Date": "",
      },
      {
        "Action Title": "Circulate updated risk register to stakeholders",
        "Meeting Name": "Weekly Standup",
        "Date Raised": "2026-03-05",
        "Action Owner": "Priya Patel",
        "Due Date": "2026-03-07",
        "Status": "Done",
        "Priority": "High",
        "Source Meeting Link": "https://meetings.example.com/standup-mar05",
        "Notes": "Sent via email and uploaded to shared drive.",
        "Closure Date": "2026-03-06",
      },
    ],
  },
  {
    id: "meeting-log-decisions-register",
    name: "Meeting Log / Decisions Register",
    description: "Record meeting outcomes, decisions, and follow-up actions in a central register.",
    category: "Project Management",
    icon: "book-open",
    columns: [
      { name: "Meeting Title", type: "text", width: 250 },
      { name: "Meeting Type", type: "select", options: ["Weekly Standup", "Project Review", "Board Meeting", "Workshop", "Ad Hoc"], width: 160 },
      { name: "Date", type: "date", width: 130 },
      { name: "Participants", type: "text", width: 250 },
      { name: "Chair", type: "person", width: 150 },
      { name: "Decisions Made", type: "text", width: 300 },
      { name: "Key Outcomes", type: "text", width: 300 },
      { name: "Follow-up Required", type: "checkbox", width: 140 },
      { name: "Linked Actions", type: "text", width: 200 },
      { name: "Documents", type: "url", width: 200 },
    ],
    sampleRows: [
      {
        "Meeting Title": "Q1 Programme Review",
        "Meeting Type": "Project Review",
        "Date": "2026-03-14",
        "Participants": "Sarah Chen, James Wilson, Priya Patel, Marcus Lee",
        "Chair": "Sarah Chen",
        "Decisions Made": "Approved budget increase for infrastructure modernisation. Deferred mobile app launch to Q3.",
        "Key Outcomes": "Revised programme plan agreed. Resource reallocation confirmed.",
        "Follow-up Required": true,
        "Linked Actions": "ACT-041, ACT-042",
        "Documents": "https://docs.example.com/q1-review-minutes",
      },
      {
        "Meeting Title": "Sprint 14 Retrospective",
        "Meeting Type": "Workshop",
        "Date": "2026-03-07",
        "Participants": "Elena Kowalski, David Okafor, Marcus Lee, Ana Torres",
        "Chair": "Elena Kowalski",
        "Decisions Made": "Adopt pair programming for complex features. Introduce automated regression tests.",
        "Key Outcomes": "Team velocity improved by 12%. Three process improvements identified.",
        "Follow-up Required": true,
        "Linked Actions": "ACT-038, ACT-039",
        "Documents": "https://docs.example.com/sprint14-retro",
      },
      {
        "Meeting Title": "Daily Engineering Standup",
        "Meeting Type": "Weekly Standup",
        "Date": "2026-03-18",
        "Participants": "David Okafor, Ana Torres, Priya Patel",
        "Chair": "David Okafor",
        "Decisions Made": "No blockers escalated. Continue current sprint plan.",
        "Key Outcomes": "All tasks on track for sprint completion.",
        "Follow-up Required": false,
        "Linked Actions": "",
        "Documents": "",
      },
    ],
  },
  {
    id: "issue-incident-tracker",
    name: "Issue / Incident Tracker",
    description: "Log and manage issues and incidents with severity classification and resolution tracking.",
    category: "Governance",
    icon: "alert-triangle",
    columns: [
      { name: "Issue Title", type: "text", width: 250 },
      { name: "Description", type: "text", width: 300 },
      { name: "Severity", type: "select", options: ["Critical", "Major", "Minor", "Cosmetic"], width: 120 },
      { name: "Priority", type: "select", options: ["P1", "P2", "P3", "P4"], width: 100 },
      { name: "Status", type: "select", options: ["New", "Investigating", "In Progress", "Resolved", "Closed"], width: 140 },
      { name: "Reported By", type: "person", width: 150 },
      { name: "Assigned To", type: "person", width: 150 },
      { name: "Impact", type: "text", width: 250 },
      { name: "Root Cause", type: "text", width: 250 },
      { name: "Resolution", type: "text", width: 250 },
      { name: "Opened Date", type: "date", width: 130 },
      { name: "Closed Date", type: "date", width: 130 },
    ],
    sampleRows: [
      {
        "Issue Title": "Payment gateway timeout during peak hours",
        "Description": "Transactions failing with 504 errors between 12:00 and 14:00 daily, affecting approximately 15% of checkout attempts.",
        "Severity": "Critical",
        "Priority": "P1",
        "Status": "In Progress",
        "Reported By": "Marcus Lee",
        "Assigned To": "Priya Patel",
        "Impact": "Revenue loss estimated at GBP 12,000 per day. Customer complaints increasing.",
        "Root Cause": "Connection pool exhaustion due to unoptimised database queries.",
        "Resolution": "",
        "Opened Date": "2026-03-12",
        "Closed Date": "",
      },
      {
        "Issue Title": "Incorrect VAT calculation on multi-currency orders",
        "Description": "VAT is being applied at the base rate regardless of customer location for orders placed in non-GBP currencies.",
        "Severity": "Major",
        "Priority": "P2",
        "Status": "Resolved",
        "Reported By": "Ana Torres",
        "Assigned To": "James Wilson",
        "Impact": "Financial compliance risk. Approximately 200 orders affected since 1 March.",
        "Root Cause": "Currency conversion applied after VAT calculation instead of before.",
        "Resolution": "Reordered tax calculation pipeline. Retroactive corrections applied to affected orders.",
        "Opened Date": "2026-03-05",
        "Closed Date": "2026-03-14",
      },
      {
        "Issue Title": "Dashboard charts not rendering on Safari 18",
        "Description": "All chart components display blank areas on Safari 18 for macOS. Console shows WebGL context errors.",
        "Severity": "Minor",
        "Priority": "P3",
        "Status": "Investigating",
        "Reported By": "Elena Kowalski",
        "Assigned To": "David Okafor",
        "Impact": "Affects approximately 8% of users on Safari. Workaround available using Chrome.",
        "Root Cause": "",
        "Resolution": "",
        "Opened Date": "2026-03-16",
        "Closed Date": "",
      },
    ],
  },
  {
    id: "risk-register",
    name: "Risk Register",
    description: "Identify, assess, and track risks with probability, impact, and mitigation plans.",
    category: "Governance",
    icon: "shield-alert",
    columns: [
      { name: "Risk Title", type: "text", width: 250 },
      { name: "Description", type: "text", width: 300 },
      { name: "Category", type: "select", options: ["Technical", "Financial", "Operational", "Legal", "Reputational"], width: 140 },
      { name: "Probability", type: "select", options: ["Very High", "High", "Medium", "Low", "Very Low"], width: 130 },
      { name: "Impact", type: "select", options: ["Critical", "High", "Medium", "Low", "Negligible"], width: 130 },
      { name: "Risk Score", type: "number", width: 110 },
      { name: "Owner", type: "person", width: 150 },
      { name: "Mitigation Plan", type: "text", width: 300 },
      { name: "Status", type: "select", options: ["Open", "Mitigating", "Accepted", "Closed"], width: 130 },
      { name: "Review Date", type: "date", width: 130 },
    ],
    sampleRows: [
      {
        "Risk Title": "Key developer departure during critical phase",
        "Description": "Lead architect has indicated potential departure in Q2, creating knowledge concentration risk for core platform.",
        "Category": "Operational",
        "Probability": "Medium",
        "Impact": "High",
        "Risk Score": 12,
        "Owner": "Sarah Chen",
        "Mitigation Plan": "Initiate knowledge transfer sessions. Document architecture decisions. Begin recruitment for backup resource.",
        "Status": "Mitigating",
        "Review Date": "2026-04-01",
      },
      {
        "Risk Title": "Third-party API deprecation",
        "Description": "Primary mapping provider has announced API v2 sunset for September 2026. Migration to v3 requires significant refactoring.",
        "Category": "Technical",
        "Probability": "Very High",
        "Impact": "Medium",
        "Risk Score": 15,
        "Owner": "David Okafor",
        "Mitigation Plan": "Allocate sprint capacity for migration starting Q2. Evaluate alternative providers as contingency.",
        "Status": "Open",
        "Review Date": "2026-03-25",
      },
      {
        "Risk Title": "Data protection regulation changes",
        "Description": "Proposed amendments to data processing requirements may affect customer data handling procedures across all platforms.",
        "Category": "Legal",
        "Probability": "Low",
        "Impact": "Critical",
        "Risk Score": 8,
        "Owner": "Ana Torres",
        "Mitigation Plan": "Monitor regulatory updates monthly. Engage legal counsel for impact assessment. Prepare contingency data handling procedures.",
        "Status": "Open",
        "Review Date": "2026-04-15",
      },
    ],
  },
  {
    id: "change-request-tracker",
    name: "Change Request Tracker",
    description: "Manage change requests through submission, review, and approval workflows.",
    category: "Governance",
    icon: "git-pull-request",
    columns: [
      { name: "Change Title", type: "text", width: 250 },
      { name: "Description", type: "text", width: 300 },
      { name: "Requestor", type: "person", width: 150 },
      { name: "Business Impact", type: "select", options: ["High", "Medium", "Low"], width: 140 },
      { name: "Priority", type: "select", options: ["Critical", "High", "Medium", "Low"], width: 120 },
      { name: "Status", type: "select", options: ["Draft", "Submitted", "Under Review", "Approved", "Rejected", "Implemented"], width: 150 },
      { name: "Approval Status", type: "select", options: ["Pending", "Approved", "Rejected"], width: 140 },
      { name: "Approver", type: "person", width: 150 },
      { name: "Target Release", type: "text", width: 150 },
      { name: "Linked Items", type: "text", width: 200 },
    ],
    sampleRows: [
      {
        "Change Title": "Add single sign-on integration with Azure AD",
        "Description": "Enable enterprise customers to authenticate via Azure Active Directory, reducing onboarding friction and improving security posture.",
        "Requestor": "Marcus Lee",
        "Business Impact": "High",
        "Priority": "High",
        "Status": "Approved",
        "Approval Status": "Approved",
        "Approver": "Sarah Chen",
        "Target Release": "v3.2.0",
        "Linked Items": "RISK-007, TASK-142",
      },
      {
        "Change Title": "Migrate report generation to asynchronous processing",
        "Description": "Move all report generation to background workers to eliminate timeouts on large data sets and improve user experience.",
        "Requestor": "Elena Kowalski",
        "Business Impact": "Medium",
        "Priority": "Medium",
        "Status": "Under Review",
        "Approval Status": "Pending",
        "Approver": "James Wilson",
        "Target Release": "v3.3.0",
        "Linked Items": "INC-023",
      },
      {
        "Change Title": "Replace legacy notification system",
        "Description": "Decommission email-only notification system and replace with multi-channel approach supporting email, in-app, and SMS.",
        "Requestor": "Priya Patel",
        "Business Impact": "High",
        "Priority": "Critical",
        "Status": "Submitted",
        "Approval Status": "Pending",
        "Approver": "Sarah Chen",
        "Target Release": "v4.0.0",
        "Linked Items": "CR-015, RISK-012",
      },
    ],
  },
  {
    id: "raid-log",
    name: "RAID Log",
    description: "Consolidated log for Risks, Actions, Issues, and Decisions with RAG status tracking.",
    category: "Governance",
    icon: "layout-list",
    columns: [
      { name: "Item Title", type: "text", width: 250 },
      { name: "Type", type: "select", options: ["Risk", "Action", "Issue", "Decision"], width: 120 },
      { name: "Description", type: "text", width: 300 },
      { name: "Owner", type: "person", width: 150 },
      { name: "Status", type: "select", options: ["Open", "In Progress", "Closed", "Escalated"], width: 130 },
      { name: "Priority", type: "select", options: ["High", "Medium", "Low"], width: 120 },
      { name: "Date Raised", type: "date", width: 130 },
      { name: "Due Date", type: "date", width: 130 },
      { name: "Resolution", type: "text", width: 250 },
      { name: "RAG Status", type: "rag", width: 120 },
    ],
    sampleRows: [
      {
        "Item Title": "Finalise data migration strategy",
        "Type": "Action",
        "Description": "Complete technical design for migrating 2.4M records from legacy Oracle database to PostgreSQL with zero downtime.",
        "Owner": "David Okafor",
        "Status": "In Progress",
        "Priority": "High",
        "Date Raised": "2026-03-01",
        "Due Date": "2026-03-21",
        "Resolution": "",
        "RAG Status": "Amber",
      },
      {
        "Item Title": "Budget overrun on cloud infrastructure",
        "Type": "Risk",
        "Description": "Current cloud spend is trending 18% above forecast due to unoptimised container scaling policies.",
        "Owner": "Priya Patel",
        "Status": "Escalated",
        "Priority": "High",
        "Date Raised": "2026-03-08",
        "Due Date": "2026-03-22",
        "Resolution": "",
        "RAG Status": "Red",
      },
      {
        "Item Title": "Adopt trunk-based development model",
        "Type": "Decision",
        "Description": "Team agreed to move from feature branching to trunk-based development with feature flags to accelerate delivery cadence.",
        "Owner": "Elena Kowalski",
        "Status": "Closed",
        "Priority": "Medium",
        "Date Raised": "2026-02-25",
        "Due Date": "2026-03-05",
        "Resolution": "Implemented trunk-based workflow. Feature flag framework deployed. Team onboarding completed.",
        "RAG Status": "Green",
      },
    ],
  },
  {
    id: "crm-opportunity-pipeline",
    name: "CRM / Opportunity Pipeline",
    description: "Track sales opportunities through pipeline stages with deal values and close probabilities.",
    category: "Business",
    icon: "trending-up",
    columns: [
      { name: "Account", type: "text", width: 180 },
      { name: "Contact", type: "text", width: 160 },
      { name: "Opportunity Name", type: "text", width: 250 },
      { name: "Stage", type: "select", options: ["Prospecting", "Qualification", "Proposal", "Negotiation", "Closed Won", "Closed Lost"], width: 150 },
      { name: "Deal Value", type: "number", width: 130 },
      { name: "Probability %", type: "number", width: 120 },
      { name: "Owner", type: "person", width: 150 },
      { name: "Next Action", type: "text", width: 250 },
      { name: "Close Date", type: "date", width: 130 },
      { name: "Source", type: "select", options: ["Referral", "Website", "Event", "Cold Call", "Partner"], width: 130 },
    ],
    sampleRows: [
      {
        "Account": "Meridian Financial Group",
        "Contact": "Robert Hargreaves",
        "Opportunity Name": "Enterprise platform licence - 500 seats",
        "Stage": "Negotiation",
        "Deal Value": 245000,
        "Probability %": 75,
        "Owner": "Ana Torres",
        "Next Action": "Send revised pricing proposal with volume discount structure.",
        "Close Date": "2026-04-15",
        "Source": "Referral",
      },
      {
        "Account": "Northern Healthcare Trust",
        "Contact": "Dr. Fiona McAllister",
        "Opportunity Name": "Clinical workflow management system",
        "Stage": "Proposal",
        "Deal Value": 180000,
        "Probability %": 50,
        "Owner": "Marcus Lee",
        "Next Action": "Present technical architecture to IT governance board.",
        "Close Date": "2026-05-30",
        "Source": "Event",
      },
      {
        "Account": "Apex Manufacturing Ltd",
        "Contact": "Thomas Brennan",
        "Opportunity Name": "Supply chain analytics module",
        "Stage": "Qualification",
        "Deal Value": 95000,
        "Probability %": 30,
        "Owner": "James Wilson",
        "Next Action": "Schedule discovery workshop with operations team.",
        "Close Date": "2026-06-20",
        "Source": "Website",
      },
    ],
  },
  {
    id: "resource-capacity-board",
    name: "Resource & Capacity Board",
    description: "Monitor team resource allocation, capacity, and availability across projects.",
    category: "Business",
    icon: "users",
    columns: [
      { name: "Resource Name", type: "text", width: 180 },
      { name: "Role", type: "select", options: ["Developer", "Designer", "PM", "Analyst", "QA", "Architect"], width: 130 },
      { name: "Project", type: "text", width: 200 },
      { name: "Task", type: "text", width: 220 },
      { name: "Allocation %", type: "number", width: 120 },
      { name: "Capacity", type: "number", width: 110 },
      { name: "Assigned Hours", type: "number", width: 130 },
      { name: "Start Date", type: "date", width: 130 },
      { name: "End Date", type: "date", width: 130 },
      { name: "Manager", type: "person", width: 150 },
      { name: "Status", type: "select", options: ["Available", "Allocated", "Over-allocated", "On Leave"], width: 150 },
    ],
    sampleRows: [
      {
        "Resource Name": "David Okafor",
        "Role": "Developer",
        "Project": "Customer Portal v2",
        "Task": "API integration layer",
        "Allocation %": 80,
        "Capacity": 40,
        "Assigned Hours": 32,
        "Start Date": "2026-03-10",
        "End Date": "2026-04-04",
        "Manager": "Sarah Chen",
        "Status": "Allocated",
      },
      {
        "Resource Name": "Elena Kowalski",
        "Role": "QA",
        "Project": "Analytics Platform",
        "Task": "Regression test suite development",
        "Allocation %": 100,
        "Capacity": 40,
        "Assigned Hours": 40,
        "Start Date": "2026-03-17",
        "End Date": "2026-03-28",
        "Manager": "James Wilson",
        "Status": "Allocated",
      },
      {
        "Resource Name": "Ana Torres",
        "Role": "Designer",
        "Project": "Mobile App Redesign",
        "Task": "Onboarding flow prototypes",
        "Allocation %": 120,
        "Capacity": 40,
        "Assigned Hours": 48,
        "Start Date": "2026-03-10",
        "End Date": "2026-03-21",
        "Manager": "Sarah Chen",
        "Status": "Over-allocated",
      },
    ],
  },
  {
    id: "stakeholder-register",
    name: "Stakeholder Register",
    description: "Map and manage stakeholders with influence, interest, and engagement strategies.",
    category: "Business",
    icon: "contact",
    columns: [
      { name: "Stakeholder Name", type: "text", width: 180 },
      { name: "Organisation", type: "text", width: 200 },
      { name: "Role", type: "text", width: 180 },
      { name: "Influence Level", type: "select", options: ["Very High", "High", "Medium", "Low"], width: 140 },
      { name: "Interest Level", type: "select", options: ["Very High", "High", "Medium", "Low"], width: 140 },
      { name: "Engagement Strategy", type: "select", options: ["Manage Closely", "Keep Satisfied", "Keep Informed", "Monitor"], width: 170 },
      { name: "Primary Contact", type: "person", width: 150 },
      { name: "Communication Frequency", type: "select", options: ["Weekly", "Fortnightly", "Monthly", "Quarterly"], width: 180 },
      { name: "Notes", type: "text", width: 300 },
      { name: "Last Contact Date", type: "date", width: 140 },
    ],
    sampleRows: [
      {
        "Stakeholder Name": "Catherine Blackwell",
        "Organisation": "Meridian Financial Group",
        "Role": "Chief Information Officer",
        "Influence Level": "Very High",
        "Interest Level": "High",
        "Engagement Strategy": "Manage Closely",
        "Primary Contact": "Sarah Chen",
        "Communication Frequency": "Weekly",
        "Notes": "Key decision-maker for platform adoption. Prefers concise written updates with executive dashboards.",
        "Last Contact Date": "2026-03-14",
      },
      {
        "Stakeholder Name": "Richard Townsend",
        "Organisation": "Apex Manufacturing Ltd",
        "Role": "Head of Operations",
        "Influence Level": "High",
        "Interest Level": "Very High",
        "Engagement Strategy": "Manage Closely",
        "Primary Contact": "James Wilson",
        "Communication Frequency": "Fortnightly",
        "Notes": "Strong advocate for digital transformation. Keen to pilot new features and provide feedback.",
        "Last Contact Date": "2026-03-08",
      },
      {
        "Stakeholder Name": "Margaret Liu",
        "Organisation": "Compliance Partners LLP",
        "Role": "Regulatory Affairs Director",
        "Influence Level": "Medium",
        "Interest Level": "Low",
        "Engagement Strategy": "Keep Informed",
        "Primary Contact": "Ana Torres",
        "Communication Frequency": "Quarterly",
        "Notes": "Interested primarily in data governance and compliance reporting capabilities.",
        "Last Contact Date": "2026-01-20",
      },
    ],
  },
  {
    id: "objectives-okr-tracker",
    name: "Objectives & OKR Tracker",
    description: "Define and track objectives with measurable key results, targets, and progress.",
    category: "Strategy",
    icon: "target",
    columns: [
      { name: "Objective", type: "text", width: 280 },
      { name: "Key Result", type: "text", width: 280 },
      { name: "Owner", type: "person", width: 150 },
      { name: "Period", type: "select", options: ["Q1", "Q2", "Q3", "Q4", "Annual"], width: 110 },
      { name: "Target Metric", type: "number", width: 130 },
      { name: "Current Value", type: "number", width: 130 },
      { name: "Status", type: "select", options: ["On Track", "At Risk", "Behind", "Achieved"], width: 130 },
      { name: "Confidence Level", type: "select", options: ["High", "Medium", "Low"], width: 140 },
      { name: "Linked Initiatives", type: "text", width: 250 },
    ],
    sampleRows: [
      {
        "Objective": "Increase platform adoption across enterprise segment",
        "Key Result": "Achieve 150 new enterprise accounts by end of Q2",
        "Owner": "Ana Torres",
        "Period": "Q2",
        "Target Metric": 150,
        "Current Value": 87,
        "Status": "On Track",
        "Confidence Level": "High",
        "Linked Initiatives": "Enterprise Sales Campaign, Partner Channel Expansion",
      },
      {
        "Objective": "Improve product reliability and performance",
        "Key Result": "Reduce P1 incident count to fewer than 3 per month",
        "Owner": "David Okafor",
        "Period": "Q1",
        "Target Metric": 3,
        "Current Value": 5,
        "Status": "At Risk",
        "Confidence Level": "Medium",
        "Linked Initiatives": "Infrastructure Modernisation, Observability Programme",
      },
      {
        "Objective": "Strengthen customer retention and satisfaction",
        "Key Result": "Achieve Net Promoter Score of 65 or above",
        "Owner": "Marcus Lee",
        "Period": "Annual",
        "Target Metric": 65,
        "Current Value": 61,
        "Status": "On Track",
        "Confidence Level": "Medium",
        "Linked Initiatives": "Customer Success Programme, Product Feedback Loop",
      },
    ],
  },
  {
    id: "lessons-learned-register",
    name: "Lessons Learned Register",
    description: "Capture and share lessons from projects to continuously improve processes and delivery.",
    category: "Strategy",
    icon: "lightbulb",
    columns: [
      { name: "Lesson Title", type: "text", width: 250 },
      { name: "Project/Initiative", type: "text", width: 200 },
      { name: "Category", type: "select", options: ["Process", "Technical", "People", "Communication", "Planning"], width: 140 },
      { name: "What Went Well", type: "text", width: 300 },
      { name: "What Could Improve", type: "text", width: 300 },
      { name: "Recommendations", type: "text", width: 300 },
      { name: "Owner", type: "person", width: 150 },
      { name: "Date Captured", type: "date", width: 130 },
      { name: "Status", type: "select", options: ["Documented", "Under Review", "Implemented", "Shared"], width: 140 },
      { name: "Impact Area", type: "multi_select", options: ["Project Management", "Development", "Design", "Testing", "Operations"], width: 220 },
    ],
    sampleRows: [
      {
        "Lesson Title": "Early stakeholder engagement reduced change requests by 40%",
        "Project/Initiative": "Customer Portal v2",
        "Category": "Communication",
        "What Went Well": "Involving key stakeholders in design sprints from week one led to clearer requirements and fewer late-stage changes.",
        "What Could Improve": "Stakeholder availability was inconsistent. Need dedicated time slots agreed upfront.",
        "Recommendations": "Mandate stakeholder participation agreements at project kickoff. Schedule recurring design review sessions in advance.",
        "Owner": "Sarah Chen",
        "Date Captured": "2026-03-10",
        "Status": "Shared",
        "Impact Area": ["Project Management", "Design"],
      },
      {
        "Lesson Title": "Automated testing caught 85% of regression defects before release",
        "Project/Initiative": "Analytics Platform",
        "Category": "Technical",
        "What Went Well": "Investment in comprehensive automated test suite paid dividends in release confidence and speed.",
        "What Could Improve": "Test execution time grew to 45 minutes. Need to parallelise test runs.",
        "Recommendations": "Adopt parallel test execution framework. Set a maximum test suite runtime target of 15 minutes.",
        "Owner": "Elena Kowalski",
        "Date Captured": "2026-03-05",
        "Status": "Implemented",
        "Impact Area": ["Development", "Testing"],
      },
      {
        "Lesson Title": "Underestimated data migration complexity delayed go-live by 3 weeks",
        "Project/Initiative": "Infrastructure Modernisation",
        "Category": "Planning",
        "What Went Well": "Rollback procedures worked effectively when initial migration attempt encountered data integrity issues.",
        "What Could Improve": "Estimation did not account for data cleansing requirements or edge cases in legacy data formats.",
        "Recommendations": "Include data profiling and cleansing as explicit workstream in migration plans. Add 30% contingency buffer for data-related tasks.",
        "Owner": "David Okafor",
        "Date Captured": "2026-02-28",
        "Status": "Under Review",
        "Impact Area": ["Project Management", "Operations"],
      },
    ],
  },
];

export const TEMPLATE_CATEGORIES = [
  "Project Management",
  "Governance",
  "Business",
  "Strategy",
] as const;
