/** System templates — Tier 1 (Module 17 §2.7) */
export const SYSTEM_SURVEY_TEMPLATES = [
  {
    key: "change-readiness",
    title: "Change Readiness Assessment",
    description: "Assess business readiness using Likert and rating questions across ADKAR dimensions.",
    surveyType: "Change Readiness",
    category: "Change Management",
    questions: [
      { text: "I understand why this change is happening.", type: "likert", required: true },
      { text: "I understand how this change will affect my role.", type: "likert", required: true },
      { text: "I have the knowledge needed to work in the new way.", type: "likert", required: true },
      { text: "I have the ability to work in the new way.", type: "likert", required: true },
      { text: "I am motivated to work in the new way.", type: "likert", required: true },
      { text: "How confident are you that the organisation is ready for go-live?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "What is your biggest concern about this change?", type: "para", required: false },
    ],
  },
  {
    key: "post-go-live",
    title: "Post Go-Live Satisfaction",
    description: "Collect user satisfaction after system implementation.",
    surveyType: "Post Go-Live",
    category: "Client Satisfaction",
    questions: [
      { text: "Overall, how satisfied are you with the new system?", type: "sc", required: true },
      { text: "How would you rate the quality of training you received?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "Has the system improved your day-to-day productivity?", type: "yn", required: true },
      { text: "How responsive was the support team during go-live?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "What issues are you still experiencing?", type: "para", required: false },
      { text: "How likely are you to recommend this system to a colleague?", type: "nps", required: true },
    ],
  },
  {
    key: "training-needs",
    title: "Training Needs Analysis",
    description: "Identify users needing training on specific topics.",
    surveyType: "Training Needs",
    category: "Onboarding",
    questions: [
      { text: "Which modules do you use most frequently?", type: "cb", options: ["Finance", "Procurement", "HR", "Sales", "Reporting"], required: true },
      { text: "How confident do you feel using the system?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "Which topics would you like additional training on?", type: "para", required: true },
      { text: "Preferred training format", type: "mc", options: ["In-person workshop", "Virtual classroom", "Self-paced e-learning", "Quick reference guides"], required: true },
      { text: "How many hours per week do you spend in the system?", type: "mc", options: ["Less than 5", "5–15", "15–30", "More than 30"], required: false },
    ],
  },
  {
    key: "project-health",
    title: "Project Health Check",
    description: "Stakeholder assessment of scope, schedule, budget, risks, and morale.",
    surveyType: "Project Health",
    category: "Retrospective",
    questions: [
      { text: "How would you rate overall project progress?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "Is the project on schedule?", type: "yn", required: true },
      { text: "Is the project within budget?", type: "yn", required: true },
      { text: "How effectively are risks being managed?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "How would you rate team morale?", type: "sc", required: true },
      { text: "What is the single biggest risk to project success?", type: "para", required: false },
    ],
  },
  {
    key: "stakeholder-satisfaction",
    title: "Stakeholder Satisfaction",
    description: "Periodic client survey using NPS-style rating and open-ended feedback.",
    surveyType: "Stakeholder Satisfaction",
    category: "Client Satisfaction",
    questions: [
      { text: "How satisfied are you with our overall service?", type: "sc", required: true },
      { text: "How likely are you to recommend us?", type: "nps", required: true },
      { text: "How well do we understand your business needs?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "How would you rate communication from the project team?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "What could we improve?", type: "para", required: false },
    ],
  },
  {
    key: "sprint-retrospective",
    title: "End of Sprint Retrospective",
    description: "Agile team survey on what went well and what to improve.",
    surveyType: "Retrospective",
    category: "Retrospective",
    questions: [
      { text: "What went well this sprint?", type: "para", required: true },
      { text: "What didn't go well?", type: "para", required: true },
      { text: "What should we try next sprint?", type: "para", required: true },
      { text: "How would you rate sprint goal achievement?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "Team collaboration this sprint", type: "likert", required: true },
    ],
  },
  {
    key: "uat-readiness",
    title: "UAT Readiness Check",
    description: "Checks if testers, data, and environments are ready before UAT begins.",
    surveyType: "UAT Readiness",
    category: "Quality Assurance",
    questions: [
      { text: "Are UAT test scripts prepared and reviewed?", type: "yn", required: true },
      { text: "Is test data available and validated?", type: "yn", required: true },
      { text: "Are UAT environments stable and accessible?", type: "yn", required: true },
      { text: "Are testers identified and available?", type: "yn", required: true },
      { text: "How ready is the team to start UAT?", type: "scale", scaleMin: 1, scaleMax: 10, required: true },
      { text: "List any blockers to UAT start", type: "para", required: false },
    ],
  },
  {
    key: "team-pulse",
    title: "Team Pulse Check",
    description: "Weekly morale check with emoji ratings on wellbeing.",
    surveyType: "Team Pulse",
    category: "Team Wellbeing",
    questions: [
      { text: "How are you feeling this week?", type: "sc", ratingDisplay: "emoji", required: true },
      { text: "How manageable is your workload?", type: "scale", scaleMin: 1, scaleMax: 5, scaleMinLabel: "Overwhelmed", scaleMaxLabel: "Comfortable", required: true },
      { text: "Do you feel supported by your team?", type: "yn", required: true },
      { text: "Anything you'd like leadership to know?", type: "para", required: false },
    ],
  },
  {
    key: "post-resolution-csat",
    title: "Post-Resolution CSAT",
    description: "Automatically triggered when a Help Desk ticket is closed. Collects client satisfaction and writes the score back to the ticket.",
    surveyType: "Help Desk CSAT",
    category: "Help Desk",
    locked: true,
    settings: {
      anonymous: false,
      showProgress: false,
      onePerPage: false,
      showResultsToRespondents: false,
      closeDaysAfterDispatch: 3,
    },
    questions: [
      {
        text: "How satisfied are you with the resolution of this ticket?",
        type: "sc",
        ratingDisplay: "stars",
        scaleMin: 1,
        scaleMax: 5,
        scaleMinLabel: "Very dissatisfied",
        scaleMaxLabel: "Very satisfied",
        required: true,
      },
      { text: "Any additional comments or feedback?", type: "para", required: false },
    ],
  },
] as const;

export const LIKERT_OPTIONS = [
  "Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree",
];

export const DEFAULT_LIKERT_COLS = LIKERT_OPTIONS;
